name: obdreader2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_bluetooth_serial: ^0.4.0

  obd2_plugin:
    git:
      url: https://github.com/begaz/OBDII.git
      ref: main

  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.2.15

flutter:
  uses-material-design: true

  assets:
    - assets/bluetooth_connected.png
    - assets/icon/app_icon.png
    - assets/splash.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android: true
  ios: true
